version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: smart_ids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
    environment:
      - DB_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch

  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./suricata/rules:/etc/suricata/rules
      - suricata_logs:/var/log/suricata

  rule_updater:
    build:
      context: ./rule_updater
      dockerfile: Dockerfile
    volumes:
      - ./suricata/rules:/app/rules

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - aggregator
    environment:
      - AGGREGATOR_BASE_URL=http://aggregator:5000

volumes:
  suricata_logs: