
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: smart_ids
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  aggregator:
    build: .
    command: python aggregator.py
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
    environment:
      - DB_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_HOST=elasticsearch

  suricata:
    build: .
    command: suricata -i ${NETWORK_INTERFACE:-eth0} -c /etc/suricata/suricata.yaml --set eve.outputs[0].file=/var/log/suricata/eve.json
    depends_on:
      - rabbitmq
    network_mode: host
    volumes:
      - ./rules:/etc/suricata/rules
      - suricata_logs:/var/log/suricata

  sensor:
    build: .
    command: python ids.py --mode live
    depends_on:
      - rabbitmq
      - suricata
    network_mode: host

  rule_updater:
    build: .
    command: python update_rules.py
    volumes:
      - ./rules:/app/rules

volumes:
  suricata_logs:
